export const SET_SNIPPET = "SET_SNIPPET";
export const SET_SNIPPET_LANGUAGE = "SET_SNIPPET_LANGUAGE"
export const SET_SNIPPET_TITTLE = "SET_SNIPPET_TITLE"
export const SET_SNIPPET_SAVE = "SET_SNIPPET_SAVE"
export const SET_SNIPPET_VIEW = "SET_SNIPPET_VIEW"